export const user_fields = [
  {
    name: "name",
    title: "Name",
    placeholder: "John",
    type: "text",
    description: "This is your name",
    className: "w-90",
  },
  {
    name: "age",
    title: "Age",
    placeholder: "24",
    type: "number",
    description: "Current Age",
    className: "w-90",
  },
  {
    name: "contact",
    title: "Contact",
    placeholder: "639123456788",
    type: "number",
    description: "Phone Number",
    className: "w-90",
  },
  {
    name: "position",
    title: "Position",
    placeholder: "Software Developer",
    type: "text",
    description: "Current Position",
    className: "w-90",
  },
  {
    name: "skills",
    title: "Skills",
    placeholder: "",
    type: "multi-select",
    description: "",
    className: "w-185",
  },
  {
    name: "address",
    title: "Address",
    placeholder: "USA, Cubao",
    type: "textarea",
    description: "Current Address",
    className: "w-138",
  },
   {
    name: "work_experience",
    title: "Work Experience",
    placeholder: "Company 1 - Dancer",
    type: "textarea",
    description: "Work Experience",
    className: "w-138",
    rows: 5,
  },
];

export const skill_options = [
  { label: "React", value: "react" },
  { label: "Tailwind", value: "tailwind" },
  { label: "JavaScript", value: "javascript" },
  { label: "Node.js", value: "node-js" },
  { label: "Express", value: "express" },
  { label: "MongoDB", value: "mongodb" },
  { label: "TypeScript", value: "typescript" },
  { label: "Figma", value: "figma" },
  { label: "Adobe XD", value: "adobe-xd" },
  { label: "Sketch", value: "sketch" },
  { label: "Docker", value: "docker" },
  { label: "Kubernetes", value: "kubernetes" },
  { label: "AWS", value: "aws" },
  { label: "React Native", value: "react-native" },
  { label: "Flutter", value: "flutter" },
  { label: "Swift", value: "swift" },
  { label: "Python", value: "python" },
  { label: "SQL", value: "sql" },
  { label: "Power BI", value: "power-bi" },
  { label: "Agile", value: "agile" },
  { label: "Scrum", value: "scrum" },
  { label: "Jira", value: "jira" },
  { label: "Selenium", value: "selenium" },
  { label: "Jest", value: "jest" },
  { label: "Cypress", value: "cypress" },
  { label: "Network Security", value: "network-security" },
  { label: "Penetration Testing", value: "penetration-testing" },
  { label: "Linux", value: "linux" },
];
